name: Dagger Container

on:
  workflow_dispatch:

jobs:
  dagger1:
    runs-on: ubuntu-latest
    container:
      image: registry.dagger.io/engine:v0.18.14
    steps:
      - uses: actions/checkout@v3
      - name: Call first Dagger module
        run: dagger -m github.com/libbyf/dagger-module@main call container-echo --string-arg libby