name: Github Actions - Build and Test

on:
  workflow_dispatch:

jobs:
  cicd-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Java
        uses: libbyf/github-actions-poc/.github/actions/cicd/build@main
        with:
          component_type: micro-service
          language: java
          version: 17
          source: ./java-app
      - name: Test Java
        uses: libbyf/github-actions-poc/.github/actions/cicd/build-and-test@main
        with:
          component_type: micro-service
          language: java
          version: 17
          source: ./java-app
      - name: Build Python
        uses: libbyf/github-actions-poc/.github/actions/cicd/build@main
        with:
          component_type: micro-service
          language: python
          version: '3.10'
          source: ./python-app
      - name: Test Python
        uses: libbyf/github-actions-poc/.github/actions/cicd/build-and-test@main
        with:
          component_type: micro-service
          language: python
          version: '3.10'
          source: ./python-app