name: Local Submodules Build and Test

on:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # needed to allow fetching history
      - name: Update submodules to latest on their branch
        run: |
             git submodule foreach '
               branch=$(git config -f $toplevel/.gitmodules submodule.$name.branch)
               echo "Fetching latest for $name on branch $branch"
               git fetch origin $branch
               git checkout origin/$branch
             '
      - name: Install curl and dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Test Module
        run: dagger -m ./sub-modules call container-echo --string-arg libby
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Build Java
        run: dagger -m ./sub-modules call build --component-type micro-service --language java --version 17 --source ./java-app
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Test Java
        run: dagger -m ./sub-modules call test --component-type micro-service --language java --version 17 --source ./java-app
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Build Python
        run: dagger -m ./sub-modules call build --component-type micro-service --language python --version 3.10 --source ./python-app
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Test Python
        run: dagger -m ./sub-modules call test --component-type micro-service --language python --version 3.10 --source ./python-app
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

