name: Local Submodules Module

on:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install curl and dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Call first module
        run: dagger -m ./sub-modules call container-echo --string-arg libby
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Call second module
        run: dagger -m ./sub-modules call container-echo --string-arg rita
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

