name: Remote Module Without Install Dagger

on:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install curl and dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Call remote Dagger module
        run: dagger -m github.com/libbyf/dagger-module@main call container-echo --string-arg libby

